steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/assignment-k8s/K8s/container1', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/assignment-k8s/K8s/container1']

images:
- 'us-central1-docker.pkg.dev/assignment-k8s/K8s/container1'