steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/assignment-k8s/k8-assignment/container1', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/assignment-k8s/k8-assignment/container1']

images:
- 'us-central1-docker.pkg.dev/assignment-k8s/k8-assignment/container1'